---
- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart sql-console
  ansible.builtin.systemd:
    name: sql-console
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Enable system-monitor timer
  ansible.builtin.systemd:
    name: system-monitor.timer
    state: started
    enabled: yes
