CREATE DATABASE IF NOT EXISTS syslogs;
USE syslogs;

CREATE TABLE IF NOT EXISTS stats (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  timestamp DATETIME NOT NULL,
  cpu_usage DOUBLE,
  memory_usage DOUBLE
);